"""Initial migration.

Revision ID: 8c5c5885c734
Revises: 
Create Date: 2023-09-21 16:18:25.108249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5c5885c734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyce_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_voyce_device_MAC'), ['MAC'])
        batch_op.create_unique_constraint(batch_op.f('uq_voyce_device_SN'), ['SN'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyce_device', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_voyce_device_SN'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_voyce_device_MAC'), type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
